In [50]:
import pandas as pd
df = pd.read_csv('SampleSuperstore.csv', encoding="latin1")
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

Bu qatorda datasetni tekshirib oldik nimalar bor yoki yo'qligini

In [20]:
print("Shape:", df.shape)
print("Info:", df.info())
print("Describe:", df.describe())
print(df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())

Shape: (9994, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB
Info: None
Describe:             Row ID   Postal Code         Sales     Quantity     Discount  \
count  9994.000000   9994.000000   9994.000000  9994.000000  9994.000000
mean   4997.500000  55190.379428    229.858001     3.789574     0.156203
std    2885.163629  32063.693350    623.245101     2.225110     0.206452
min       1.000000   1040.000000      0.444000     1.000000     0.000000
25%    2499.250000  23223.000000     17.280000     2.000000     0.000000
50%    4997.500000  56430.500000     54.490000     3.000000     0.200000
75%    7495.750000  90008.000000    209.940000     5.000000     0.200000
max    9994.000000  99301.000000  22638.480000    14.000000     0.800000

            Profit
count  9994.000000
mean     28.656896
std     234.260108
min   -6599.978000
25%       1.728750
50%       8.666500
75%      29.364000
max    8399.976000
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64
Duplicate rows: 0

bu qatroda datesetning o'lchamini (shape) aniqladik va asosiy ma'lumotlarni oldik uning string, object, int medianasi, mean yoki min/max, bo'sh qiymatlar, nusxalangan qatorlarni aniqlab oldik

In [6]:
print(df.isnull().sum())

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [11]:
df['Sales'] = df['Sales'].fillna(df['Sales'].median())

In [14]:
df['Ship Mode'].fillna(df['Ship Mode'].mode()[0], inplace=True)

/tmp/ipykernel_1380/1405203345.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Ship Mode'].fillna(df['Ship Mode'].mode()[0], inplace=True)

bu 2 qatorda Sales va Ship modedagi bo'sh kataklarni to'ldirik. Salesda bo'sh bo'lsa uning medianasi yozildi, Ship mode'da mode, yani medianada o'rtadagi qiymatni yozgan bo'lsa mode'da eng ko'p takrorlangani yozildi.

In [15]:
print(df.isnull().sum())

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

there was no missing value

In [18]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [21]:
df = df.drop_duplicates()
print("Shapes after removing duplicates:", df.shape)

Shapes after removing duplicates: (9994, 21)

datasetda duplicatlar yoq va drop duplicate - duplicatlarni olib tashlagandan so'ng datasetning o'lchami(shape) tekshirildi va duplicates = 0 bo'lgani uchun shape ham o'zgarmadi

In [31]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
print(df.dtypes)
df[['Order Date', 'Ship Date']].head(10)

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

  Order Date  Ship Date
0 2016-11-08 2016-11-11
1 2016-11-08 2016-11-11
2 2016-06-12 2016-06-16
3 2015-10-11 2015-10-18
4 2015-10-11 2015-10-18
5 2014-06-09 2014-06-14
6 2014-06-09 2014-06-14
7 2014-06-09 2014-06-14
8 2014-06-09 2014-06-14
9 2014-06-09 2014-06-14

order date va ship date larni datetimega o'zgartirdik. birinchi qatordagi kodga qarasak datasetdagi  sanalar  quyidagicha: 1/8/2016. bu qatordagi koddan so'ng sanalar quyidagicha: 2016-11-08. bundan maqsad avval string holatda bo'lsa hozir datetime holatda bu orqali analizda string holatda to'g'ri malumot ola olmaydi shuning uchun uni datetimega o'tkazib to'girlab qo'ydik

In [47]:
total_spending = df.groupby('Customer ID')['Sales'].sum().reset_index()
total_spending.columns = ['Customer ID', 'total_spending']
total_spending.head()
order_freq = df.groupby('Customer ID')['Order ID'].nunique().reset_index()
order_freq.columns = ['Customer ID', 'order_frequency']
order_freq.head(8)
avg_order = df.groupby('Customer ID')['Sales'].mean().reset_index()
avg_order.columns = ['Customer ID', 'avg_order_value']
avg_order.head(8)
customer_summary = total_spending.merge(order_freq, on='Customer ID') \
                                 .merge(avg_order, on='Customer ID')

bunda har bir xaridor bir necha marotaba buyurtma bergan bo'lishi mumkin. shuning uchun biz groupby orqali bir xaridor umumiy necha marta buyurtma berganini nunique orqali aniqladik, .sum orqali umumiy qancha summaga buyurtma berganini aniqladik, mean orqali har bir buyurtmasi o'rtacha qanchaga tushganini aniqladik. shunda bizda A B C D ... xaridorlar bolsa, A (B, C...) xaridor necha marta buyurtma berdi, umumiy summa qancha bo'ldi, har bir buyurtma o'rtacha qanchaga tushganini yangi jadvalda aks ettrirldi va yangi fayl qilib saqlandi.

  Customer ID  order_frequency
0    AA-10315                5
1    AA-10375                9
2    AA-10480                4
3    AA-10645                6
4    AB-10015                3
5    AB-10060                8
6    AB-10105               10
7    AB-10150                5

  Customer ID  avg_order_value
0    AA-10315       505.778182
1    AA-10375        70.426000
2    AA-10480       149.209333
3    AA-10645       282.607500
4    AB-10015       147.692667
5    AB-10060       430.867778
6    AB-10105       723.678550
7    AB-10150        80.559167

In [49]:
df.to_csv('superstore_cleaned.csv', index=False)
customer_summary.to_csv('customer_summary.csv', index=False)